---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-scheduler-extender
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-scheduler-extender
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-scheduler-extender
subjects:
- kind: ServiceAccount
  name: custom-scheduler-extender
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: custom-scheduler-extender
  apiGroup: rbac.authorization.k8s.io