apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler-extender
  namespace: kube-system
  labels:
    app: custom-scheduler-extender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-scheduler-extender
  template:
    metadata:
      labels:
        app: custom-scheduler-extender
    spec:
      serviceAccountName: custom-scheduler-extender
      containers:
      - name: scheduler-extender
        image: custom-scheduler-extender:latest  # TODO: Replace with your actual image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        env:
        - name: PORT
          value: "8888"
        # TODO: Add orchestrator address environment variable when implementing metrics
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8888
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 10