# # if running prometheus in k8s, use this config
# global:
#   scrape_interval: 10s 
#   evaluation_interval: 10s 

# scrape_configs:
#   - job_name: "ebpf_profiler"
#     kubernetes_sd_configs:
#       - role: pod
#     relabel_configs:
#       - source_labels: [__meta_kubernetes_pod_label_app]
#         regex: ebpf-profiler
#         action: keep
#       - source_labels: [__meta_kubernetes_pod_container_port_number]
#         target_label: __address__
#         replacement: "kubernetes.default.svc.cluster.local:5000"
# # https://stackoverflow.com/questions/63672816/prometheus-kubernetes-sd-config-pod-annotation-present


# if using a local (meaning running outside k8s) prometheus, use this config
global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "ebpf_profiler"
    static_configs:
      - targets: ["localhost:9000"]  