apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-hog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-hog
  template:
    metadata:
      labels:
        app: cpu-hog
    spec:
      containers:
      - name: stress-ng
        image: polinux/stress-ng
        command: ["stress-ng"]
        args: ["--cpu", "4", "--timeout", "300s"]  # Use 4 CPU cores for 300 seconds
        resources:
          limits:
            cpu: "4"
            memory: "512Mi"
          requests:
            cpu: "4"
            memory: "512Mi"