apiVersion: apps/v1
kind: Deployment
metadata:
  name: io-intensive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: io-intensive
  template:
    metadata:
      labels:
        app: io-intensive
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-172-31-5-123
      containers:
      - name: stress
        image: polinux/stress-ng
        args:
        - --io
        - "8"
        - --hdd
        - "4"
        - --hdd-bytes
        - "4G"
        - --timeout
        - "0"
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
          limits:
            cpu: "3"
            memory: "4Gi"
