apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-intensive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-intensive
  template:
    metadata:
      labels:
        app: memory-intensive
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-172-31-11-31
      containers:
      - name: stress
        image: polinux/stress-ng
        args:
        - --vm
        - "2"
        - --vm-bytes
        - "1500M"
        - --vm-method
        - all
        - --timeout
        - "0"
        resources:
          requests:
            cpu: "1"
            memory: "3Gi"
          limits:
            cpu: "2"
            memory: "4Gi"