apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-hog
  template:
    metadata:
      labels:
        app: memory-hog
    spec:
      containers:
      - name: stress-ng
        image: alpine:latest
        command: ["stress-ng"]
        args: ["--vm", "2", "--vm-bytes", "1G", "--timeout", "300s"]  # Use 2 workers to allocate 1GB each
        resources:
          limits:
            memory: "2Gi"
          requests:
            memory: "2Gi"