apiVersion: apps/v1
kind: Deployment
metadata:
  name: mixed-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mixed-workload
  template:
    metadata:
      labels:
        app: mixed-workload
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-172-31-11-42
      containers:
      - name: stress
        image: polinux/stress-ng
        args:
        - --cpu
        - "3"
        - --vm
        - "2"
        - --vm-bytes
        - "2G"
        - --io
        - "4"
        - --timeout
        - "0"
        resources:
          requests:
            cpu: "4"
            memory: "4Gi"
          limits:
            cpu: "5"
            memory: "6Gi"