apiVersion: v1
kind: Pod
metadata:
  name: cpu-benchmark
spec:
  restartPolicy: Never
  containers:
  - name: sysbench
    image: severalnines/sysbench
    command:
    - /bin/bash
    - -c
    - |
      echo "=== CPU Benchmark ===" > /tmp/results.txt
      echo "Start time: $(date)" >> /tmp/results.txt
      sysbench cpu --cpu-max-prime=20000 run >> /tmp/results.txt 2>&1
      echo "End time: $(date)" >> /tmp/results.txt
      cat /tmp/results.txt
      sleep 3600