apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ebpf-profiler
  labels:
    app: ebpf-profiler
spec:
  selector:
    matchLabels:
      app: ebpf-profiler
  template:
    metadata:
      labels:
        app: ebpf-profiler
    spec:
      hostPID: true
      # hostNetwork: true # uncomment this line if you want to use host network - this is what was causing the DNS res issues for each of the profiler pods
      containers:
      - name: ebpf-profiler
        image: emmettlsc/ebpf-profiler:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: ORCHESTRATOR_URL
          value: "http://orchestrator-service.default.svc.cluster.local:5000/update_metrics"  # env to send metrics to (so no hardcoding)
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName # this is so all nodes spawned are unique an data can be serperable in prometheus
        ports:
        - containerPort: 9000 # ken's metrics server port
        volumeMounts:
        - name: bpf-maps
          mountPath: /sys/fs/bpf
        - name: debugfs
          mountPath: /sys/kernel/debug
      volumes:
      - name: bpf-maps
        hostPath:
          path: /sys/fs/bpf
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
      terminationGracePeriodSeconds: 10