apiVersion: v1
kind: Pod
metadata:
  name: memory-pressure-pod
spec:
  nodeName: <NODE A NAME>
  containers:
  - name: memory-hog
    image: polinux/stress
    args:
    - stress
    - --vm
    - "3"
    - --vm-bytes
    - "1G"
    - --vm-keep
    - --timeout
    - "1h"