apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
  labels:
    app: custom-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-scheduler
  template:
    metadata:
      labels:
        app: custom-scheduler
    spec:
      nodeSelector:
        kubernetes.io/role: control-plane
      containers:
      - name: custom-scheduler
        image: emmettlsc/custom-scheduler-plugin:latest
        imagePullPolicy: Always
        command: ["/app/custom-scheduler"]