apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
profiles:
- schedulerName: custom-scheduler
  plugins:
    score:
      enabled:
      - name: CustomScorer